#!/bin/sh

uci -q batch <<-EOF >/dev/null
	set dhcp.@dnsmasq[0].localuse=1
	commit dhcp
	delete ucitrack.@myproxy[-1]
	add ucitrack myproxy
	set ucitrack.@myproxy[-1].init=myproxy
	commit ucitrack
	delete ucitrack.@myproxy_server[-1]
	add ucitrack myproxy_server
	set ucitrack.@myproxy_server[-1].init=myproxy_server
	commit ucitrack
	set uhttpd.main.max_requests=50
	commit uhttpd
EOF

[ ! -s "/etc/config/myproxy" ] && cp -f /usr/share/myproxy/0_default_config /etc/config/myproxy
touch /etc/config/myproxy_show >/dev/null 2>&1
rm -f /tmp/luci-indexcache
rm -rf /tmp/luci-modulecache/
killall -HUP rpcd 2>/dev/null
exit 0
