#!/bin/sh

[[ "$ACTION" == "ifup" && "$INTERFACE" == "wan" && $(uci get "myproxy.@global[0].enabled") == "1" ]] && {
    /etc/init.d/myproxy restart
    echo "myproxy: restart when wan ifup" > /dev/kmsg
}

